### ISSUE TITLE
Parse FontFamily Correctly

### ISSUE THREAD

**Issue by ismailsunni** [geoblocks/mapfishprint#33]
Currently, the OpenLayers's font family is taken as it is ([see here](https://github.com/geoblocks/mapfishprint/blob/main/src/VectorEncoder.ts#L524)). While on MFP, it needs `fontWeight`, `fontSize`, and `fontFamily` separately.

Based on the documentation here, the font on OpenLayers is defined as CSS font. So we need to parse it correctly.

**Comment by gberaudo** [comment]
Fixed in #34 .
